version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django_web
    ports:
      - "8888:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: task_tracker_lms
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  elastic_data:
    name: elastic_tracker_data