version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env