[project]
name = "tasktracker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.3",
    "djangorestframework>=3.16.0",
    "pytest>=8.4.1",
    "pytest-django>=4.11.1",
]
